const text = {
  scrapeDate: '20191007',
  title: 'Can medical care exist without plastic?',
  author: 'SARAH GIBBENS',
  text: `UNLIKE REFUSING A straw at a restaurant, it’s difficult to cut down on plastic while strapped unconscious to an operating table. Single-use plastic is facing more scrutiny than it ever has, and the medical industry could be the area where individual consumers have the least say.

  Practice Greenhealth, a non-profit that works to make hospitals more sustainable, estimates that 25 percent of the waste generated by a hospital is plastic. A study on a single hysterectomy found that the procedure can produce up to 20 pounds of waste, most of which is plastic.
  
  Single-use plastic can be an attractive option for hospitals—cheap, durable, and easily tossed out—and each new fresh plastic container or covering offers a newly sterile environment. That’s why clinicians cover themselves and everything they use in plastic.
  `
}

export default text
